# Generated by Django 5.0.1 on 2026-02-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="e_invite_image",
            field=models.ImageField(
                blank=True, upload_to="event_invitation/e_invites/"
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="event_invitation/qr_codes/"),
        ),
    ]
