# Generated by Django 5.0.1 on 2026-03-20 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0004_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="invitations.event",
            ),
        ),
    ]
