# Generated by Django 5.0.6 on 2026-03-20 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0006_backfill_default_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="invitations.event",
            ),
        ),
    ]
