# Generated by Django 5.0.1 on 2026-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0007_alter_invitation_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="security_pin",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
