# Generated by Django 5.0.1 on 2026-03-25 18:13

import invitations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0009_event_whatsapp_message_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=invitations.models.event_template_path
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="e_invite_image",
            field=models.ImageField(
                blank=True, upload_to=invitations.models.invitation_einvite_path
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="qr_code",
            field=models.ImageField(
                blank=True, upload_to=invitations.models.invitation_qr_path
            ),
        ),
    ]
