# Generated by Django 5.0.1 on 2026-03-27 16:16

from django.db import migrations


class Migration(migrations.Migration):
    """
    Renamed indexes were already applied by 0014_event_theme_fields on the
    main branch. This migration is a no-op dependency bridge so that
    0015_email_verified (from the google-auth branch) can chain correctly.
    """

    dependencies = [
        ("invitations", "0014_event_theme_fields"),
    ]

    operations = []
