# Generated by Django 5.0.1 on 2026-03-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0013_invitation_analytics_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invitation",
            new_name="invitations_event_i_d31380_idx",
            old_name="invitation_event_6d57df_idx",
        ),
        migrations.RenameIndex(
            model_name="invitation",
            new_name="invitations_event_i_0b0495_idx",
            old_name="invitation_event_4d9e36_idx",
        ),
        migrations.RenameIndex(
            model_name="invitation",
            new_name="invitations_event_i_5f0e1c_idx",
            old_name="invitation_event_16c73a_idx",
        ),
        migrations.AddField(
            model_name="event",
            name="theme",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="event",
            name="theme_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
