# Generated by Django 5.0.1 on 2026-03-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0014_rename_invitation_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(default=True),
        ),
    ]
