# Generated by Django 5.0.1 on 2026-03-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0015_email_verified"),
    ]

    operations = []
