# Generated by Django 5.0.1 on 2026-05-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0016_merge_0014_event_theme_fields_0015_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="whatsapp_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
