# Generated by Django 5.0.1 on 2026-05-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0018_invitation_images_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='whatsapp_message_template',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_whatsapp_message_template',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
