# Generated by Django 5.0.1 on 2026-05-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0020_add_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='rsvp_attending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='rsvp_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['event', 'rsvp_attending'], name='invitations_event_i_52a9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['event', 'rsvp_responded_at'], name='invitations_event_i_5ee2ec_idx'),
        ),
    ]
