# Generated by Django 5.0.1 on 2026-05-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0021_invitation_rsvp_attending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='seat_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
