# Generated by Django 5.0.1 on 2026-05-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0023_event_google_maps_url_event_hotel_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="features",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
